### ISSUE TITLE
Add stop() method & fix a rollover problem

### ISSUE THREAD

**Issue by timwilson235** [alextaujenis/RBD_Timer#1]
A stop() method on the timer would be useful. In addition, there is currently a rollover problem (albeit one that would show up very rarely). Consider this very simple example:

RBD::Timer timer;

setup() {
    Serial.begin(9600);
    timer.setTimeout(5000);
    timer.restart();
}

loop() {
    if( timer.onExpired() ) {
        Serial.println( "Expired!");
    }
}

This code will print "Expired!" when millis() is 5000; BUT, about 70 days later, when millis() rolls over and returns to 5000 again, it will print "Expired" again. This probably isn't what's desired. To fix this, and add the stop() method, the timer needs to have 3 internal states - INACTIVE, ACTIVE, EXPIRED. I suggest the following:

[code] 
// .h
# ifndef RBD_TIMER_H
# define RBD_TIMER_H
# include "Arduino.h"

namespace RBD {
  class Timer {
    public:
      void setTimeout(unsigned long value); // set/change how long until the timer expires in milliseconds
      void setHertz(int value);             // set/change how many times the timer can be restarted in one second
      void restart();                       // reset and start the timer
      void stop();                          // stop the timer
      bool isActive();                      // check if time is left
      bool isExpired();                     // returns true if time has run out
      bool onRestart();                     // returns true if the timer is expired and restarts the timer automatically
      bool onActive();                      // returns true once the timer is active, then waits for it to expire and go active again
      bool onExpired();                     // returns true once the timer is expired, then waits for it to go active and expire again
      unsigned long getValue();             // how many milliseconds that have passed since the start of the timer
      unsigned long getInverseValue();      // how many milliseconds the timer has until finished
      int getPercentValue();                // how much time has passed as a percentage of the interval
      int getInversePercentValue();         // how much time is left as a percentage of the interval

```
private:

  unsigned long _timeout;               // how long this timer should run for
  unsigned long _waypoint;              // the point in time the timer was started or reset

  void updateState();
  enum {INACTIVE, ACTIVE, EXPIRED} _state = INACTIVE;

  bool _has_been_active  = false;
  bool _has_been_expired = false;
```

  };
}
# endif

[/code]

[code]
// .cpp
# include <Arduino.h>
# include "RBD_Timer.h"

namespace RBD {
  void Timer::setTimeout(unsigned long value) {
    _timeout = value;
  }

  void Timer::setHertz(int value) {
    if(value > 0 && value < 1001) {
      _timeout = (unsigned long)(1000 / value);
    }
  }

  void Timer::restart() {
    _waypoint = millis();
    _state = ACTIVE;
  }

  void Timer::stop() {
    _state = INACTIVE;
  }

  bool Timer::isActive() {
    updateState();
    return _state == ACTIVE;
  }

  bool Timer::isExpired() {
    updateState();
    return _state == EXPIRED;
  }

  bool Timer::onRestart() {
    if( isExpired() ) {
      restart();
      return true;
    }
    return false;
  }

  bool Timer::onActive() {
    if(isActive()) {
      if(!_has_been_active) {
        _has_been_active = true;
        return true;
      }
      return false;
    }
    else {
      _has_been_active = false;
      return false;
    }
  }

  bool Timer::onExpired() {
    if(isExpired()) {
      if(!_has_been_expired) {
        _has_been_expired = true;
        return true;
      }
      return false;
    }
    else {
      _has_been_expired = false;
      return false;
    }
  }

  unsigned long Timer::getValue() {
    return millis() - _waypoint;
  }

  unsigned long Timer::getInverseValue() {
    return _timeout - getValue();
  }

  int Timer::getPercentValue() {
    return int(getValue() / float(_timeout) \* 100);
  }

  int Timer::getInversePercentValue() {
    return 100 - getPercentValue();
  }

  void Timer::updateState() {
    if( (_state == ACTIVE) && (getValue() >= _timeout) )
        _state = EXPIRED;
  }
}
[/code]

**Comment by alextaujenis** [comment]
This sounds like a great idea. Before trying to tackle this refactor I decided to pin the current Timer functionality with tests that can be found here [unit_test.ino](https://github.com/alextaujenis/RBD_Timer/blob/master/extras/unit_test/unit_test.ino) that run via [ArduinoUnit](https://github.com/mmurdoch/arduinounit).

**Comment by alextaujenis** [comment]
So I refactored the entire class in the direction of having the state held in an enum, but in order to keep the timer working the right way this refactor actually didn't solve the rollover issue. I git reset to before the refactor and realized the only problem was: _has_been_active = false; and _has_been_expired = false; needed to move into the restart() method. This actually removed code and allowed me to optimize the onActive and onExpired methods, while also fixing the rollover issue.

The timer rollover issue is fixed in [Timer v1.0.5](https://github.com/alextaujenis/RBD_Timer/releases/tag/1.0.5)

If you still feel the need for a stop() method then please open another issue on this topic. Thank you again for bringing up this rollover issue; it forced me to back the Timer with tests, fix another issue on top of this, and actually make both onActive and onExpired much faster.

**Comment by timwilson235** [comment]
OK, I am applying my changes for stop() to 1.0.5 and it all looks pretty
good. One question: I sort of feel that the timer should be in "INACTIVE"
state after construction rather than "EXPIRED" - it just feels more correct
to me (although it really doesn't matter, I guess, since who cares what the
state is before the first restart()?). But if I do construct into INACTIVE
that makes the constructor test fail, since the test wants EXPIRED.

So I would propose constructing into INACTIVE and changing the test. But I
could also just construct into EXPIRED.

What's your opinion? It's your library after all.

On Fri, Nov 20, 2015 at 11:58 AM, Alex Taujenis notifications@github.com
wrote:

> So I refactored the entire class in the direction of having the state held
> in an enum, but in order to keep the timer working the right way this
> refactor actually didn't solve the rollover issue. So I git reset to before
> the refactor and realized the only problem was: _has_been_active = false;
> and _has_been_expired = false; needed to move into the restart() method.
> This actually removed code and allowed me to optimize the onActive and
> onExpired methods, while also fixing the rollover issue.
> 
> This is fixed in Timer v1.0.5
> https://github.com/alextaujenis/RBD_Timer/releases/tag/1.0.5
> 
> If you still feel the need for a stop() method then please open another
> issue on this topic. Thank you again for bringing up this rollover issue;
> it forced me to back the Timer with tests, fix another issue on top of
> this, and actually made both onActive and onExpired much faster.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alextaujenis/RBD_Timer/issues/1#issuecomment-158494655
> .

## 

"If I have not seen as far as other men, it is because giants have stood on
my shoulders"

**Comment by alextaujenis** [comment]
This library is written with dependents that rely on the premise that the timer starts expired. When rewriting this library with the stop() method; constructing it in the INACTIVE state breaks the ability to begin a continuous loop and immediately fire an event. For example:

``` Arduino
    #include <RBD_Timer.h>

    RBD::Timer timer;

    void setup() {
      timer.setTimeout(1000 * 60 * 60); // 1 hour timeout
    }

    void loop() {
      if(timer.isExpired()) {
        // run this logic then wait an hour and do it again
        timer.restart();
      }
    }
```

If we start expired: the logic above runs immediately and we can see results, then we know it has entered a 1 hour loop. If we start inactive, then we have to call restart() to get the timer going and this will only allow us to test that logic 1 hour from now.

So I experimented with the same INACTIVE on start idea but it just didn't work, and it felt like I was providing a neutered timer from the get-go that someone had to baby-sit to get it to do things, which also had a problem I couldn't fix without adding even more code onto the pile.

**Comment by alextaujenis** [comment]
Also, a heavy consideration I have in all of this is the Motor, Button, and Light libraries are dependent upon this library. Any performance hit this library takes will manifest as poor performance in three of the main libraries of this framework (or performance gains as just happened). I'm happy that I removed code, fixed two bugs, and optimized this library for getting nailed in the Arduino loop() for v1.0.5 without adding any extra overhead. I didn't feel so good after putting in the logic to maintain 3 states.

I'd like to see your refactor but I'm still not convinced the library needs a stop() method. Now that the overflow issue is fixed, is there still a use-case for the stop() method?

**Comment by timwilson235** [comment]
OK, it's a simple matter to start out EXPIRED.

I think you're overly concerned about performance hit - a line of code plus
or minus isn't going to make a noticeable difference, one would have to add
a whole glob of code to affect anything. And I certainly haven't done
anything like that. It would be pretty hard to add that much code to this
simple class!

If you really don't want the stop() method, fine - I don't know if it's
absolutely necessary or not, it's just something that I would usually
expect to see in a timer library.

But aside from that there's still a bug in 1.0.5, related to clock
rollover. You fixed the case where onExpired and onActive would return true
after rollover - but isExpired and isActive still don't work correctly on
rollover. To illustrate, here's 2 tests I added - 1.0.5 fails both of
these, mine passes both:

  test(isExpired_should_remain_true_on_timer_rollover) {
    timer.setTimeout(1);
    timer.restart();

```
delay(1);
assertTrue(timer.isExpired());

timer.setTimeout(5); // make it active again without calling restart:
```

almost like timer rollover

```
assertTrue(timer.isExpired());
```

  }

  test(isActive_should_remain_false_on_timer_rollover) {
    timer.setTimeout(1);
    timer.restart();

```
delay(1);
assertFalse(timer.isActive());

timer.setTimeout(5); // make it active again without calling restart:
```

almost like timer rollover

```
assertFalse(timer.isActive());
```

  }

Don't know if you care about this, I admit it's a failure that's unlikely
to arise in any practical use of the timer.

If you just want the fix for this without the stop() method, I can do that
too. Take a look at the attached code files. However, once the code is
changed this way, then adding in the stop() method requires very little
additional modification. If you're concerned about the overhead of the call
to _updateState() in both isActive() and isExpired() - you really shouldn't
be - but if you are, then that function could simply be inlined.

On Fri, Nov 20, 2015 at 9:08 PM, Alex Taujenis notifications@github.com
wrote:

> Also, the last heavy consideration I have in all of this is the Motor,
> Button, and Light libraries are dependent upon this library. Any
> performance hit this library takes will manifest as poor performance in all
> three of the main libraries of this framework. I was happy to remove code,
> fix a bug, and optimize the library for getting nailed in the Arduino
> loop() for v1.0.5 without adding any extra overhead.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alextaujenis/RBD_Timer/issues/1#issuecomment-158585955
> .

## 

"If I have not seen as far as other men, it is because giants have stood on
my shoulders"

**Comment by alextaujenis** [comment]
Can you fork this library and push your changes with the stop() method? I'd like to see your full implementation.

**Comment by alextaujenis** [comment]
https://github.com/alextaujenis/RBD_Timer/pull/2
