### ISSUE TITLE
RBD::Timer

### ISSUE THREAD

**Issue by yelkenli1** [alextaujenis/RBD_Timer#10]
BN: Arduino/Genuino Uno
VID: 2A03
PID: 0043
ide: 1.6.9 

I want to run a motor for 15 seconds, every hour (for testing, I am running it for 10 seconds every 1 minute).  I chose the RBD::timer library for the timing.  The functions seemed to be the right ones.  

I originally called 'RBD::Timer dayTimer(##)';  with a number for ##, at the top outside of setup() and loop() etc., and was able to get the timer to count down from the value ##.  
It would also enter the ".getInverseValue" if-then statement at 10 seconds and execute the serial.print statement.  However, it would never enter the "isExpired" if-then statement, and therefore would never turn off the motor.  
Also, the turnTimer would expire and reset, but it would reset to a number around 4 294 967 242 (32 bits I assume).

I then removed the ## from the timer definition and used ".setTimeout(##) in the setup() function.  
When I did this, I got an error 
In function 'void setup()': DHTtester:48: error: request for member 'setTimeout' in 'dayTimer', which is of non-class type 'RBD::Timer()'  dayTimer.setTimeout(600000); 

I got one of these each time I used the RBD members in setup() or loop(). 

I searched for this error and got some hits, but did not follow.  Can you let me know some thoughts.  I copied the RBD folder to my arduino library folder, and 1.3.0 shows installed in the manage libraries.  
```arduino
#include "RBD_Timer.h"

#include "DHT.h"
#define DHTPIN 2     // what digital pin we're connected to


int motorPin = 4;   // the pin that controls the motor


RBD::Timer dayTimer();
RBD::Timer turnTimer();



#define DHTTYPE DHT22   // DHT 22  (AM2302), AM2321
DHT dht(DHTPIN, DHTTYPE);


void setup() {
  Serial.begin(9600);
  Serial.println("DHTxx test!");

  dht.begin();  

  dayTimer.setTimeout(600000);
  dayTimer.restart();
  turnTimer.setTimeout(60000);
  turnTimer.restart();

   pinMode(motorPin,OUTPUT);  // motor transistor on/off

  }




void loop() {

if (turnTimer.isExpired()) 
  {
    // timer just expired, then restarted
    // code only runs once per restart
    Serial.println("1 hour passed");
    digitalWrite(motorPin, LOW);   // the motor should have been running via the getInverseValue call
    turnTimer.restart();    //turnTimerTimeout
  }




  Serial.print("turnTimer elapsed: ");
  Serial.print(turnTimer.getValue());  
  Serial.print("    remaining: ");
  Serial.print(turnTimer.getInverseValue());
  Serial.print("      //      ");
  Serial.print("dayTimer elapsed: ");
  Serial.print(dayTimer.getValue());  
  Serial.print("    remaining: ");
  Serial.println(dayTimer.getInverseValue());



if (turnTimer.getInverseValue() < 10000)         // if 15 seconds remaining, then turn on the motor.  onRestart, turn off the motor   motorCycle*1000
  {
  digitalWrite(motorPin, HIGH);                 // turn on the motor
  Serial.println("Passed 15 second mark");
  }

if (dayTimer.onExpired()) {
    // code only runs once per event
    turnTimer.stop();            // stop the turnTimer since 19 days has elapsed
    digitalWrite(motorPin, LOW);   // make sure the motor is not running
    Serial.println("End of 19 days");
  }


}
```

Thanks!
Ted

**Comment by lauro-ojeda** [comment]
Hi there,
I wouldn't say it is an issue but it may be something to improve in the next releases.

I'm testing this great addon to dealing with time so I made a simple sketch to test it. I initiated 3 classes (i'll need 5) and managed to control it.

Happens that it takes an average of 1.3 seconds to the class start its job. So when I send a letter A,B or C, it was supposed to lit an LED immediatelly for the timing set on the code. Yes, it does the job, but it takes an average of 1.3 seconds before responding (lit the corresponding LED).

In order to see what happens, I print dashes in the end to see if the Arduino board is responding quickly enough and it is as supposed. So I get loads of dashes in the meantime after sending the signal and the phisycal response of the board (both the LED lightening plus on the serial monitor).

In that sense I presume the delay lies either somewhere in my code (if that's the case, where the issue is?) or on the class tracking time.

So, what can I do to make the response to be faster?

I'm using a Nano board connected physically via USB to my PC.

Please check my testing code below and let me know if there's something I'm doing incorrectly.

```arduino
#include <RBD_Timer.h> // https://github.com/alextaujenis/RBD_Timer

RBD::Timer timerA;
RBD::Timer timerB;
RBD::Timer timerC;

int ledA = 3;
int ledB = 4;
int ledC = 5;

int tmpA = 5000;
int tmpB = 6000;
int tmpC = 10000;

String lido;

void setup() {
  Serial.begin(9600);
  timerA.setTimeout(tmpA);
  timerB.setTimeout(tmpB);
  timerC.setTimeout(tmpC);
  timerA.restart();
  timerB.restart();
  timerC.restart();

  pinMode(ledA, OUTPUT);
  pinMode(ledB, OUTPUT);
  pinMode(ledC, OUTPUT);

  digitalWrite(ledA, LOW);
  digitalWrite(ledB, LOW);
  digitalWrite(ledC, LOW);

  Serial.println("Start");
}

void pumpOn(int pump){
  digitalWrite(pump, 1);
}

void pumpOff(int pump){
  digitalWrite(pump, 0);
}


void loop() {
  if (Serial.available() > 0) {
    lido = Serial.readString();
    
    if (lido == "A") 
        timerA.restart();
    else if (lido == "B")
        timerB.restart();
    else if(lido == "C")
        timerC.restart();
  }
  
// Timer A
    if (timerA.onActive()) {
      Serial.println("TimerA on");
      
      pumpOn(ledA);
    }

    if(timerA.onExpired()){
      Serial.println("TimerA off");
      
      pumpOff(ledA);
    }

// Timer B
    if (timerB.onActive()) {
      Serial.println("TimerV on");
      
      pumpOn(ledB);
    }

    if(timerB.onExpired()){
      Serial.println("TimerB off");
      
      pumpOff(ledB);
    }

// Timer C
    if (timerC.onActive()) {
      Serial.println("TimerC on");
      
      pumpOn(ledC);
    }

    if(timerC.onExpired()){
      Serial.println("TimerC off");
      
      pumpOff(ledC);
    }

  //Serial.print("-");
}
```

**Comment by alextaujenis** [comment]
@yelkenli1 This is how you can run a motor for 15 seconds every hour, for 19 days.

```arduino
#include <RBD_Timer.h> // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Motor.h> // https://github.com/alextaujenis/RBD_Motor

long one_hour = 60 * 60 * 1000; // (in milliseconds)
long fifteen_seconds = 15 * 1000; // (in milliseconds)
int hour_counter = 0;
int ninteen_days = 19 * 24; // (in hours)

RBD::Timer hour_timer(one_hour);
RBD::Timer second_timer(fifteen_seconds);
RBD::Motor motor(4);

void setup() {}
 
void loop() {
  if(hour_counter < ninteen_days && hour_timer.onRestart()) {
    second_timer.restart();
    motor.on();
    hour_counter++;
  }
  
  if(second_timer.isExpired() && motor.isOn()) {
    motor.off();
  }    
}
```

**Comment by alextaujenis** [comment]
@evozenn here is an example of turning motors/pumps on for a specific period of time when accepting serial input. (Make sure your Arduino Serial Monitor is sending a `newline` character).

You can type `A`, `B`, or `C` and it will run the pumps for the specific period of time.

Your delay of 1.3 seconds might have been from the 9600 baud rate, but I'm not sure about that. There is no delay with this code below.

```arduino
#include <RBD_Timer.h> // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Motor.h> // https://github.com/alextaujenis/RBD_Motor
#include <RBD_SerialManager.h> // https://github.com/alextaujenis/RBD_SerialManager

RBD::Timer timerA(5000);
RBD::Timer timerB(6000);
RBD::Timer timerC(10000);

RBD::Motor pumpA(3);
RBD::Motor pumpB(4);
RBD::Motor pumpC(5);

RBD::SerialManager serial_manager;

void setup() {
  serial_manager.start();
  serial_manager.println("Start");

  timerA.restart();
  timerB.restart();
  timerC.restart();
}

void loop() {
  if(serial_manager.onReceive()) {
    if(serial_manager.isCmd("A")) {
      timerA.restart();
    }
    if(serial_manager.isCmd("B")) {
      timerB.restart();
    }
    if(serial_manager.isCmd("C")) {
      timerC.restart();
    }
  }

  if (timerA.onActive()) {
    pumpA.on();
    serial_manager.println("pump A on");
  }

  if(timerA.onExpired()){
    pumpA.off();
    serial_manager.println("pump A off");
  }

  if (timerB.onActive()) {
    pumpB.on();
    serial_manager.println("pump B on");
  }
  
  if(timerB.onExpired()){
    pumpB.off();
    serial_manager.println("pump B off");
  }

  if (timerC.onActive()) {
    pumpC.on();
    serial_manager.println("pump C on");
  }
  
  if(timerC.onExpired()){
    pumpC.off();
    serial_manager.println("pump C off");
  }
}
```
