### ISSUE TITLE
Problem with code

### ISSUE THREAD

**Issue by roberkas98** [alextaujenis/RBD_Timer#11]
Hello, i found your library and i think that is one of the most practical libraries to manage the time, but i cant run my code properly....is  a very simple code, but i dont know what is wrong.Could you guide me?
Thanks, that´s the code. 

```C++
#include <RBD_Timer.h>

RBD::Timer timerluz;
RBD::Timer timerosc;

int fp = 5000;
int ho = 5000;
 
void setup(){           
  Serial.begin(9600);     
  // Indicamos el pin que va a activar o desactivar la bobina del relé
  // We indicate the pin that will activate or deactivate the relay coil
  pinMode(13, OUTPUT);//Luces - lights
  digitalWrite(13, LOW);
  timerluz.setTimeout(fp);
  timerluz.restart();
}

void loop() {
  if(timerluz.onActive())
  {
    Serial.println("OFF");
    digitalWrite(13,HIGH ); //Apaga luz - Turn off light 
  }
  if(timerluz.onExpired())
  {
    timerosc.setTimeout(ho);
    timerosc.restart();    
  }
  if(timerosc.onExpired()) //Lo que pasa cuando hay luz - What happens when there is light
  { 
     Serial.println("ON");
     digitalWrite(13,LOW ); //Enciende luz - Turn on light
     timerluz.restart();
   }
}
```

**Comment by alextaujenis** [comment]
@roberkas98 I formatted and translated your sketch...

It looks like your sketch is doing this:
* Bind to the built-in Arduino light and make sure it is off
* Create a 5 second timer
* Restart the 5 second timer
* Start the loop
* Timer luz is active on the first loop - print "OFF" and turn off the light
* Timer luz is not expired on the first loop
* Timer osc is expired on the first loop - print "ON" and turn on the light, restart the timer luz
* Timer luz is active on the second loop - print "OFF" and turn off the light

I'm not quite sure what you are trying to accomplish here, maybe this?
* Start the Arduino
* Print "OFF" and turn off the Arduino light
* Wait 5 seconds
* Print "ON" and turn on the Arduino light
* Wait 5 seconds
* Print "OFF" and turn off the Arduino light
* ...

The easiest way to do this would be to just use the `RBD::Light` library here: https://robotsbigdata.com/docs-arduino-light.html

```C++

#include <RBD_Timer.h>
#include <RBD_Light.h>

RBD::Light light(13);

void setup() {  
  light.blink(5000,5000);
} 

void loop() {  
  light.update();
}
```

However if you wanted to do this with just the `RBD::Timer` library and two timers then here is the code:

```C++
#include <RBD_Timer.h>

RBD::Timer timer1(5000);
RBD::Timer timer2(5000);

void setup() {
  pinMode(13, OUTPUT);
  digitalWrite(13, LOW);
  Serial.begin(9600);
}

void loop() {
  if(timer1.onExpired()) {
    digitalWrite(13, LOW);
    Serial.println("OFF");
    timer2.restart();
  }
  if(timer2.onExpired()) {
    digitalWrite(13, HIGH);
    Serial.println("ON");
    timer1.restart();
  }
}

```
