### ISSUE TITLE
sam and samd support

### ISSUE THREAD

**Issue by waspinator** [alextaujenis/RBD_Timer#13]
Thanks for your awesome libraries!

Is there code in RBD_Timer and your other libraries which you know have compatibility issues with sam and samd processors?

**Comment by alextaujenis** [comment]
With all of the different kinds of Arduino hardware; each Robots + Big Data library has been designed for the widest compatibility available. If you can compile and run Arduino code on it; then these libraries will work and not interfere with each other or other (non RBD) libraries. I've only heard from people asking to expand the list of compatible hardware, and haven't heard a compatibility issue yet.
