### ISSUE TITLE
Timing problems

### ISSUE THREAD

**Issue by MstrLucas** [alextaujenis/RBD_Timer#15]
Hi, I'm rather new to this and I'm stuck...
The sketch does work but very irregular... it runs from start to finish in less then 3 sec.
What did I do wrong so it doesn't read the timers right?

The sketch is supposed to be a railroad crossing. Red light comes on, beams close - train passes, beams open, red light off.
Later I still want to include sound, same lenght as the LED.
Everything is triggered by one reed-switch.

This is my code (sorry for the lay-out, I'm used to BASIC)

#include <RBD_Button.h>
#include <VarSpeedServo.h>
#include <RBD_Timer.h>
  
RBD::Button button(2);
RBD::Timer timer1;
RBD::Timer timer2;
RBD::Timer timer3;
const byte LED = 4;
byte sTi = 0;                                   //start timer
byte go=0;                                     //execute after timer
VarSpeedServo myservo1;
VarSpeedServo myservo2;

void setup() 
{
  myservo1.attach(10);
  myservo2.attach(11);
  myservo1.write(90, 255, true);
  myservo2.write(90, 255, true);
  timer1.setTimeout(4000);                               // beams close after led on
  timer2.setTimeout(13000);                             //beams open 
  timer3.setTimeout (7000);                              //led goes off
  pinMode(LED, OUTPUT);
  digitalWrite(LED, LOW);
}

void loop() 
{
  if (button.onPressed()) {digitalWrite(LED, HIGH);sTi = 1;}
  if (sTi==1){if(timer1.onRestart()){go=1;} 
  if (go==1){myservo1.write(180, 30, false ); myservo2.write(180, 30, true);sTi = 2;}}
  if (sTi==2){if(timer2.onRestart()){go=2;}
  if (go==2){myservo1.write(90, 30, false ); myservo2.write(90, 30, true);sTi = 3;}}
  if (sTi==3){if(timer3.onRestart()) {go=3;}
  if (go==3){digitalWrite(LED, LOW);sTi=0;go=0;}}
}

**Comment by alextaujenis** [comment]
Well this is interesting. To understand your problem I watched a railroad crossing video, mapped the process, and found out how you are using the reed-switch (it would be helpful for you to include this kind of deep-context in future issues). Here is the railroad crossing process:

1. train triggers relay
1. lights/sound turn on at the same time
1. 5 seconds to wait for peds
1. beams come down over 12 seconds
1. sound off when beams hit bottom
1. train passes
1. beams up over 6 seconds
1. lights off when beams stop

And here are the source videos:

Railroad Crossing Signals
https://youtu.be/euWIV34kQ78?t=350

Train detection via reed switch and magnet
https://www.youtube.com/watch?v=h2gWPFGqS0k

I considered writing a sketch to tackle this process and releasing it on the https://robotsbigdata.com website, however this is a complicated process and I'm short on pro-bono time for this kind of thing. 

Please re-open this issue with a specific question about your code if you are still having an issue.
