### ISSUE TITLE
Domain Name Expiration

### ISSUE THREAD

**Issue by jigleski** [alextaujenis/RBD_Timer#16]
Thank you so much for your libraries! I am using them for a school project and it appears your domain name with GoDaddy has expired. The link you provided for documentation seems to be "pending renewal or deletion". Also I have found you motor library particularly helpful.  I adapted it to work with a motor shield which only has one direction pin instead of two to allow bi-direction control. Feel free to reach out if you would like a copy of my edits (they are a little clumsy, but they are clearly marked and get the job done without wasting a "dummy" pin on the Arduino to trick the library into working with a single directional control pin)

**Comment by alextaujenis** [comment]
Thank you for the notice about the expired domain name. My registrar had issues auto-renewing so I just took care of it. DNS should propagate the changes and bring the site back up within an hour.
