### ISSUE TITLE
Sumar mas tiempo cuando el timer esta funcionando

### ISSUE THREAD

**Issue by legnalegna1** [alextaujenis/RBD_Timer#20]
Hola,tengo un problema no puedo sumar más tiempo mientras el timer está funcionando agradecería que me pudieran ayudar, gracias

> Title: Add more time when the timer is running
> Description: Hi, I have a problem. I can't add more time while the timer is running. I would appreciate it if you could help me, thanks.

**Comment by alextaujenis** [comment]
Hola,

Se puede agregar más tiempo al temporizador, pero probablemente sea muy específico para el código de su aplicación o los requisitos funcionales. Hay dos períodos distintos en los que puede agregar tiempo al temporizador:

     1) Mientras el temporizador está funcionando.

     2) Cuando el temporizador se detiene o expira.

Hay una diferencia en la forma en que agrega tiempo al temporizador en estos diferentes escenarios, y debe tener cuidado de aislar su código dentro del bucle Arduino o, de lo contrario, podría aumentar el tiempo para siempre.

Para el primer escenario, mientras el temporizador se está ejecutando y desea agregar más tiempo antes de que caduque... simplemente puede llamar

``` c++
int mas_tiempo = 1000;
timer.setTimeout(timer.getTimeout() + mas_tiempo);
```

Si el temporizador ha expirado, se vuelve un poco más difícil. Su evento `onExpired ()` se activará y debe verificar "es realmente cuando quiero realizar la acción, o necesito más tiempo" dentro de su código. Si necesita más tiempo (quiere extender el temporizador) ahora su código se verá así (dentro del evento `onExpired()`):

``` c++
int mas_tiempo = 1000;
timer.setTimeout(mas_tiempo);
```

Como dije anteriormente: lograr que esto funcione correctamente depende en gran medida de cómo realmente desea que funcione su aplicación y su capacidad para aislar correctamente su código dentro del bucle Arduino. Espero que algo de esto tenga sentido.

Si proporciona más detalles sobre lo que realmente está tratando de hacer, incluido su código de ejemplo, podría ayudarlo con consejos más concretos.

<hr>

Hello,

Adding more time to timer can be done, but it is probably very specific to your application code or functional requirements. There are two distinct periods at which you can add time to the timer:

1) While the timer is running.

2) When the timer is stopped or expired.

There is a difference in how you add time to the timer across these different scenarios, and you need to be careful to isolate your code within the Arduino loop() or else you could be increasing the time forever.

For the first scenario, while the timer is running and you want to add more time before it expires... you can just call
``` c++
int more_time = 1000;
timer.setTimeout(timer.getTimeout() + more_time);
```

If the timer is expired it gets a little more difficult. Your `onExpired()` event will trigger and you need to check "is this really when I want to perform the action, or do I need more time" within your code. If you need more time (want to extend the timer) now your code looks like this (within the `onExpired()` event):
``` c++
int more_time = 1000;
timer.setTimeout(more_time);
```

Like I said above: getting this to work correctly is highly dependent upon how you actually want your application to function, and your ability to correctly isolate your code within the Arduino loop(). I hope some of this makes sense.

If you provide more detail on what you are actually trying to do, including your example code, I could help with more concrete advice.

**Comment by legnalegna1** [comment]
Todo funciona perfectamente excelente libreria te felicito actualmente son 8 timers funcionando al mismo tiempo lo único que cambie fue timer.setTimeout(timer.getInverseValue() + more_time); y funciona como lo necesito muchas gracias , saludos desde Mexico

**Comment by legnalegna1** [comment]
Gracias
