### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Tvault** [alextaujenis/RBD_Timer#5]
I've downloaded your RBD_Timer code with examples and presently trying to use your "timer.getValue" through serial print which only prints "0" ever second am I doing something wrong? I've tried other timer codes which have worked..... Also, my objective is to have a counter count up to 15min and triggering 4 relays at different times(event triggers) within that time frame.

void loop()
 {
    if(timer.onRestart())
       {  
          Serial.println(timer.getValue());  
       }
}

**Comment by alextaujenis** [comment]
It looks like you aren't setting a timeout value. Try getting the default example to work and move on from there.

``` arduino
#include <RBD_Timer.h>

RBD::Timer timer;

void setup() {
  Serial.begin(115200);
  timer.setTimeout(3000);
  timer.restart();
}

void loop() {
  if(timer.onRestart()) {
    Serial.println("Three seconds passed");
  }
}
```

You need to build a state machine and fire changes with timer.onRestart() to control 4 relays, then call timer.setTimeout() to change the delay for the schedule.

**Comment by Tvault** [comment]
Hello Alex,

The example worked but I'm trying to see the millis() count through serial..... If I put timer.stop(); and timer.getValue(); in a loop I see counts through serial?  If I substitute timer.stop to timer.restart I get "0's".....

Thanks for your time,

Tom

**Comment by Tvault** [comment]
Alex,

Any future developments for a "Pause"?

Thanks again,

Tom

**Comment by alextaujenis** [comment]
> The example worked but I'm trying to see the millis() count through serial...

The onRestart() method restarts the timer before executing your code, so it is correct that getValue() returns 0 inside of an onRestart() conditional. The onRestart() method is internally just a combination of calling isExpired() and restart() together. If I understand correctly; this should accomplish what you want:

``` arduino
#include <RBD_Timer.h>

RBD::Timer timer;

void setup() {
  Serial.begin(115200);
  timer.setTimeout(3000);
  timer.restart();
}

void loop() {
  if(timer.isExpired()) {
    Serial.println(timer.getValue());
    timer.restart();
  }
}
```

> Any future developments for a "Pause"?

What kind of use-case do you have for Pause? The last major change to this library was adding timer.stop() but I still haven't found a use-case for that in my projects yet...

**Comment by Tvault** [comment]
Alex,

I tried your example but all it prints is the same number.....?

I was thinking that when using the timer.getValue(); I would see this:

1000

2000

3000

4000...

 unsigned long Timer::getValue() {

return millis() - _waypoint;

I'm trying different timer/count libraries with trigger events....below is ones I've tried already.

#include "Counter.h"

  mySecond = timer.getCurrentSeconds();
  myMinute = timer.getCurrentMinutes();
  genie.WriteObject(GENIE_OBJ_LED_DIGITS, 0, myMinute);
  genie.WriteObject(GENIE_OBJ_LED_DIGITS, 1, mySecond);

#include "Timer.h"

  count = (millis());
  mySecond = count/ 1000 % 3600 % 60 % 60;
  myMinute = count / 1000 % 3600 / 60;
  genie.WriteObject(GENIE_OBJ_LED_DIGITS, 0, myMinute);
  genie.WriteObject(GENIE_OBJ_LED_DIGITS, 1, mySecond);

Thanks, Tom

**Comment by alextaujenis** [comment]
This library uses relative time, meaning the number of elapsed millis() since the timer was restarted. It does not use absolute time, where you would expect the seconds to count upward. It is not designed to track seconds/minutes/hours or the time of day, but for your example:

``` arduino
#include <RBD_Timer.h>

RBD::Timer timer(1000);
unsigned long total = 0;

void setup() {
  Serial.begin(115200);
  timer.restart();
}

void loop() {
  if(timer.onRestart()) {
    Serial.println(total += 1000);
  }
}
```
